# Generated by Django 2.1.5 on 2020-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='date',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
