# Generated by Django 2.1.5 on 2020-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.CharField(default='{}', max_length=9999999),
        ),
    ]
