# Generated by Django 3.0.6 on 2020-05-15 13:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_auto_20200513_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=255)),
                ('cardNumber', models.CharField(max_length=16)),
                ('expirationDate', models.CharField(max_length=5)),
                ('CVC', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='street', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
