# Generated by Django 2.1.5 on 2020-05-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Captain', '0002_products_manufacturer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImages',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
    ]
