# Generated by Django 3.0.5 on 2020-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200508_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.CharField(blank=True, max_length=9999999),
        ),
    ]
